//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PruebasSPEntityWeb
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    using System.Data.Entity.Core.Objects;
    using System.Linq;
    
    public partial class COMISIONESEntities : DbContext
    {
        public COMISIONESEntities()
            : base("name=COMISIONESEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
    
        public virtual ObjectResult<csp_ConsultarFacturas_Result> csp_ConsultarFacturas(Nullable<int> idEmpresa, string empresa, string idVendedor, Nullable<int> periodo, Nullable<System.DateTime> fechaInicio, Nullable<System.DateTime> fechaFin, string clientes)
        {
            var idEmpresaParameter = idEmpresa.HasValue ?
                new ObjectParameter("idEmpresa", idEmpresa) :
                new ObjectParameter("idEmpresa", typeof(int));
    
            var empresaParameter = empresa != null ?
                new ObjectParameter("Empresa", empresa) :
                new ObjectParameter("Empresa", typeof(string));
    
            var idVendedorParameter = idVendedor != null ?
                new ObjectParameter("idVendedor", idVendedor) :
                new ObjectParameter("idVendedor", typeof(string));
    
            var periodoParameter = periodo.HasValue ?
                new ObjectParameter("Periodo", periodo) :
                new ObjectParameter("Periodo", typeof(int));
    
            var fechaInicioParameter = fechaInicio.HasValue ?
                new ObjectParameter("fechaInicio", fechaInicio) :
                new ObjectParameter("fechaInicio", typeof(System.DateTime));
    
            var fechaFinParameter = fechaFin.HasValue ?
                new ObjectParameter("fechaFin", fechaFin) :
                new ObjectParameter("fechaFin", typeof(System.DateTime));
    
            var clientesParameter = clientes != null ?
                new ObjectParameter("Clientes", clientes) :
                new ObjectParameter("Clientes", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<csp_ConsultarFacturas_Result>("csp_ConsultarFacturas", idEmpresaParameter, empresaParameter, idVendedorParameter, periodoParameter, fechaInicioParameter, fechaFinParameter, clientesParameter);
        }
    }
}
