//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace OneCoreData
{
    using System;
    using System.Collections.Generic;
    
    public partial class AA140210
    {
        public string CUSTOM { get; set; }
        public string SECTION { get; set; }
        public int DEX_ROW_ID { get; set; }
        public string ASOBSRV { get; set; }
        public string DENOMC { get; set; }
    }
}
