//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace OneCoreData
{
    using System;
    using System.Collections.Generic;
    
    public partial class AA710410
    {
        public string GRPID { get; set; }
        public string TOGID { get; set; }
        public string GRPNM { get; set; }
        public string GRPDESCE { get; set; }
        public string GRPDESCI { get; set; }
        public string TOGDESCE { get; set; }
        public string TOGDESCI { get; set; }
        public string GRPOBSVR { get; set; }
        public int DEX_ROW_ID { get; set; }
    }
}
