//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace OneCoreData
{
    using System;
    using System.Collections.Generic;
    
    public partial class CATCLAVE_PEDIMENTO
    {
        public int Id_ClavePedimento { get; set; }
        public string Clave { get; set; }
        public string Descripcion { get; set; }
        public bool Activo { get; set; }
        public System.DateTime CTL_Alta { get; set; }
        public string Usuario_Alta { get; set; }
        public Nullable<System.DateTime> CTL_Cambio { get; set; }
        public string Usuario_Cambio { get; set; }
    }
}
