//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace OneCoreData
{
    using System;
    using System.Collections.Generic;
    
    public partial class CatRoles
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public CatRoles()
        {
            this.RelUsuarioRol = new HashSet<RelUsuarioRol>();
        }
    
        public int Id_Rol { get; set; }
        public string Rol { get; set; }
        public string Descripcion { get; set; }
        public bool Activo { get; set; }
        public System.DateTime CTL_Alta { get; set; }
        public string Usuario_Alta { get; set; }
        public Nullable<System.DateTime> CTL_Cambio { get; set; }
        public string Usuario_Cambio { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<RelUsuarioRol> RelUsuarioRol { get; set; }
    }
}
