//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace OneCoreData
{
    using System;
    using System.Collections.Generic;
    
    public partial class CatUsuarios
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public CatUsuarios()
        {
            this.RelUsuarioPantalla = new HashSet<RelUsuarioPantalla>();
            this.RelUsuarioRol = new HashSet<RelUsuarioRol>();
        }
    
        public int Id_Usuario { get; set; }
        public string Login { get; set; }
        public string Password { get; set; }
        public string Nombre { get; set; }
        public string Apellido { get; set; }
        public string Oficina { get; set; }
        public string Skin { get; set; }
        public string Observaciones { get; set; }
        public Nullable<bool> Activo { get; set; }
        public string Correo { get; set; }
        public System.DateTime CTL_ALTA { get; set; }
        public string USER_ALTA { get; set; }
        public Nullable<System.DateTime> CTL_CAMBIO { get; set; }
        public string USER_CAMBIO { get; set; }
        public Nullable<int> Id_Empresa { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<RelUsuarioPantalla> RelUsuarioPantalla { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<RelUsuarioRol> RelUsuarioRol { get; set; }
    }
}
