//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace OneCoreData
{
    using System;
    using System.Collections.Generic;
    
    public partial class com_clientesComConfig
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public com_clientesComConfig()
        {
            this.com_relConceptoVendedor = new HashSet<com_relConceptoVendedor>();
        }
    
        public int idClienteConfig { get; set; }
        public int IdEmpresa { get; set; }
        public string idCliente { get; set; }
        public string strNombreCliente { get; set; }
        public int idCodigoVendedor { get; set; }
        public string idAduana { get; set; }
        public string strNombreAduana { get; set; }
        public string strTipoOp { get; set; }
        public string idPedimento { get; set; }
        public string strClavePedimento { get; set; }
        public int intDiasCredito { get; set; }
        public int intDiasRetencion { get; set; }
        public int intDiasGracia { get; set; }
        public string strTipoCosto { get; set; }
        public string strIntercia { get; set; }
        public string strNotificacion { get; set; }
        public bool boolActivo { get; set; }
        public System.DateTime dtFechaAlta { get; set; }
        public Nullable<System.DateTime> dtFechaModifica { get; set; }
        public string idUsuarioAlta { get; set; }
        public string idUsuarioModifica { get; set; }
        public string idVendedor { get; set; }
        public string strTipoCambio { get; set; }
        public string idClientePedimento { get; set; }
        public string strNombreClientePedimento { get; set; }
        public Nullable<int> intercompania { get; set; }
        public Nullable<decimal> comisionIntercom { get; set; }
        public Nullable<int> idTipoVendedor { get; set; }
    
        public virtual com_clientesComConfig com_clientesComConfig1 { get; set; }
        public virtual com_clientesComConfig com_clientesComConfig2 { get; set; }
        public virtual com_empresas com_empresas { get; set; }
        public virtual com_vendedores com_vendedores { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<com_relConceptoVendedor> com_relConceptoVendedor { get; set; }
    }
}
