//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace OneCoreData
{
    using System;
    using System.Collections.Generic;
    
    public partial class com_UsuarioVendedor
    {
        public int IdRow { get; set; }
        public Nullable<int> Id_Usuario { get; set; }
        public Nullable<int> idCodigoVendedor { get; set; }
    }
}
