//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace OneCoreData
{
    using System;
    using System.Collections.Generic;
    
    public partial class com_clientesHistoricoPeriodos
    {
        public int idHistoricoPeriodoCliente { get; set; }
        public Nullable<int> idEmpresa { get; set; }
        public string idCliente { get; set; }
        public string strNombreCliente { get; set; }
        public int idVendedor { get; set; }
        public string strNombreAduana { get; set; }
        public string strTipoOp { get; set; }
        public string idPedimento { get; set; }
        public int intDiasCredito { get; set; }
        public int intDiasRetencion { get; set; }
        public int intDiasGracia { get; set; }
        public string strTipoCosto { get; set; }
        public string strIntercia { get; set; }
        public string strNotificacion { get; set; }
        public Nullable<System.DateTime> fecha_Inicio { get; set; }
        public Nullable<System.DateTime> fecha_Fin { get; set; }
        public Nullable<int> Periodo { get; set; }
        public Nullable<bool> Activo { get; set; }
    }
}
