//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace OneCoreData
{
    using System;
    using System.Collections.Generic;
    
    public partial class com_clientesComConfigPeriodos
    {
        public int idClienteConfigPeriodo { get; set; }
        public int idClienteConfig { get; set; }
        public string idCliente { get; set; }
        public string strNombreCliente { get; set; }
        public int idCodigoVendedor { get; set; }
        public string idAduana { get; set; }
        public string strNombreAduana { get; set; }
        public string strTipoOp { get; set; }
        public string idPedimento { get; set; }
        public int intDiasCredito { get; set; }
        public int intDiasRetencion { get; set; }
        public int intDiasGracia { get; set; }
        public string strTipoCosto { get; set; }
        public string strIntercia { get; set; }
        public string strNotificacion { get; set; }
    
        public virtual com_clientesComConfig com_clientesComConfig { get; set; }
    }
}
