//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace OneCoreData
{
    using System;
    using System.Collections.Generic;
    
    public partial class com_bitacora
    {
        public int id { get; set; }
        public string nombre_usuario { get; set; }
        public string tipo { get; set; }
        public string seccion { get; set; }
        public string descripcion { get; set; }
        public System.DateTime fecha { get; set; }
    }
}
