//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace OneCoreData
{
    using System;
    using System.Collections.Generic;
    
    public partial class com_usuarios
    {
        public int idUsuario { get; set; }
        public string strNombreUsuario { get; set; }
        public string strContrasena { get; set; }
        public int idPerfil { get; set; }
        public System.DateTime dtFechaAlta { get; set; }
        public Nullable<System.DateTime> dtFechaModificacion { get; set; }
        public bool boolActivo { get; set; }
    
        public virtual com_perfiles com_perfiles { get; set; }
    }
}
