//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace OneCoreData
{
    using System;
    using System.Collections.Generic;
    
    public partial class com_perfiles
    {
        public com_perfiles()
        {
            this.com_usuarios = new HashSet<com_usuarios>();
        }
    
        public int idPerfil { get; set; }
        public string strDescripcion { get; set; }
        public bool boolActivo { get; set; }
        public System.DateTime dtFechaAlta { get; set; }
        public Nullable<System.DateTime> dtFechaModifica { get; set; }
        public string idUsuarioAlta { get; set; }
        public string idUsuarioModifica { get; set; }
    
        public virtual ICollection<com_usuarios> com_usuarios { get; set; }
    }
}
