//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace OneCoreData
{
    using System;
    using System.Collections.Generic;
    
    public partial class com_relConceptoVendedor
    {
        public int idRelConceptoVendedor { get; set; }
        public int idClienteConfig { get; set; }
        public string idConcepto { get; set; }
        public string strConcepto { get; set; }
        public string strCostoVenta { get; set; }
        public decimal dcmComision { get; set; }
        public bool boolActivo { get; set; }
        public Nullable<decimal> dDescuentoFijo { get; set; }
        public string strTipoCambio { get; set; }
    
        public virtual com_clientesComConfig com_clientesComConfig { get; set; }
    }
}
