//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace OneCoreData
{
    using System;
    using System.Collections.Generic;
    
    public partial class com_HistorialDescuentoVendedor
    {
        public int idRow { get; set; }
        public int idDescuentoConceptoVendedor { get; set; }
        public int idCodigoVendedor { get; set; }
        public int idPeriodo { get; set; }
        public decimal Descuento { get; set; }
        public decimal SaldoTotal { get; set; }
        public Nullable<int> idEmpresa { get; set; }
        public Nullable<System.DateTime> FechaInicioPeriodo { get; set; }
        public Nullable<System.DateTime> FechaFinPeriodo { get; set; }
    }
}
