//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace OneCoreData
{
    using System;
    using System.Collections.Generic;
    
    public partial class com_periodos
    {
        public int idPeriodo { get; set; }
        public int idCodigoVendedor { get; set; }
        public int strNumPeriodo { get; set; }
        public string strAño { get; set; }
        public System.DateTime dtFechaInicio { get; set; }
        public System.DateTime dtFechaFin { get; set; }
        public bool boolActivo { get; set; }
        public System.DateTime dtFechaAlta { get; set; }
        public Nullable<System.DateTime> dtFechaModifica { get; set; }
        public string idUsuarioAlta { get; set; }
        public string idUsuarioModifica { get; set; }
    
        public virtual com_vendedores com_vendedores { get; set; }
    }
}
