//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace OneCoreData
{
    using System;
    using System.Collections.Generic;
    
    public partial class com_bitacora
    {
        public int id { get; set; }
        public string nombre_usuario { get; set; }
        public string tipo { get; set; }
        public string seccion { get; set; }
        public string descripcion { get; set; }
        public System.DateTime fecha { get; set; }
    }
}
