//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace OneCoreData
{
    using System;
    using System.Collections.Generic;
    
    public partial class com_configPeriodos
    {
        public int idConfiguracionPeriodo { get; set; }
        public string idVendedor { get; set; }
        public Nullable<int> Periodo { get; set; }
        public Nullable<System.DateTime> fechaInicio { get; set; }
        public Nullable<System.DateTime> fechaFin { get; set; }
        public Nullable<bool> StatusPeriodo { get; set; }
        public Nullable<bool> Activo { get; set; }
    }
}
