//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace OneCoreData
{
    using System;
    
    public partial class csp_detalleComisiones_Result1
    {
        public string SLPRSNID { get; set; }
        public string ITEMNMBR { get; set; }
        public Nullable<decimal> XTNDPRCE { get; set; }
        public Nullable<decimal> COMISION { get; set; }
        public Nullable<decimal> SUBTOTAL { get; set; }
        public decimal TOTAL { get; set; }
        public string SOPNUMBE { get; set; }
        public string CUSTNMBR { get; set; }
        public string GrupoNombre { get; set; }
        public string ADUASECC { get; set; }
        public string REFRENCE { get; set; }
        public string IMPOEXP { get; set; }
        public string CLPEID { get; set; }
        public decimal TCFACSOP { get; set; }
        public Nullable<decimal> TCPED { get; set; }
        public int DIAS { get; set; }
        public System.DateTime DATEFACTURA { get; set; }
        public Nullable<System.DateTime> DATEPAGO { get; set; }
        public Nullable<bool> RETENCION { get; set; }
        public Nullable<bool> ACTIVO { get; set; }
        public System.DateTime DATESYS { get; set; }
        public Nullable<System.DateTime> DATEMODIFY { get; set; }
        public System.DateTime DATEENVIO { get; set; }
        public Nullable<bool> COMISIONAR { get; set; }
        public Nullable<int> PERIODO { get; set; }
        public Nullable<System.DateTime> FECHAINICIO { get; set; }
        public Nullable<System.DateTime> FECHAFIN { get; set; }
        public Nullable<int> SOPTYPE { get; set; }
        public string RENDICION { get; set; }
        public Nullable<bool> PERIO_LIBERA_RETENC { get; set; }
        public Nullable<int> ID_RULE { get; set; }
        public string NOTA { get; set; }
        public string CUSTNAME { get; set; }
    }
}
