//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace OneCoreData
{
    using System;
    
    public partial class csp_ConsultaStatusFacturas_Result1
    {
        public string DOCNUMBR { get; set; }
        public string ESTADO { get; set; }
        public string ADEUDO_DECIMAL { get; set; }
        public string PERIODO_PAGADO { get; set; }
        public Nullable<int> CONCEPTOS_COMISIONABLES { get; set; }
        public string CANCELADA { get; set; }
    }
}
