//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace OneCoreData
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class VERTICAL_V2Entities : DbContext
    {
        public VERTICAL_V2Entities()
            : base("name=VERTICAL_V2Entities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<CatRoles> CatRoles { get; set; }
        public virtual DbSet<CatUsuarios> CatUsuarios { get; set; }
        public virtual DbSet<RelUsuarioPantalla> RelUsuarioPantalla { get; set; }
        public virtual DbSet<RelUsuarioRol> RelUsuarioRol { get; set; }
    }
}
