//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace OneCoreData
{
    using System;
    using System.Collections.Generic;
    
    public partial class RelUsuarioRol
    {
        public int Id_Empresa { get; set; }
        public bool Activo { get; set; }
        public System.DateTime CTL_Alta { get; set; }
        public string Usuario_Alta { get; set; }
        public Nullable<System.DateTime> CTL_Cambio { get; set; }
        public string Usuario_Cambio { get; set; }
        public int Id_Usuario { get; set; }
        public int Id_Rol { get; set; }
    
        public virtual CatRoles CatRoles { get; set; }
        public virtual CatUsuarios CatUsuarios { get; set; }
    }
}
