//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace OneCoreData
{
    using System;
    using System.Collections.Generic;
    
    public partial class RM20101
    {
        public string CUSTNMBR { get; set; }
        public string CPRCSTNM { get; set; }
        public string DOCNUMBR { get; set; }
        public string CHEKNMBR { get; set; }
        public string BACHNUMB { get; set; }
        public string BCHSOURC { get; set; }
        public string TRXSORCE { get; set; }
        public short RMDTYPAL { get; set; }
        public short CSHRCTYP { get; set; }
        public string CBKIDCRD { get; set; }
        public string CBKIDCSH { get; set; }
        public string CBKIDCHK { get; set; }
        public System.DateTime DUEDATE { get; set; }
        public System.DateTime DOCDATE { get; set; }
        public System.DateTime POSTDATE { get; set; }
        public string PSTUSRID { get; set; }
        public System.DateTime GLPOSTDT { get; set; }
        public System.DateTime LSTEDTDT { get; set; }
        public string LSTUSRED { get; set; }
        public decimal ORTRXAMT { get; set; }
        public decimal CURTRXAM { get; set; }
        public decimal SLSAMNT { get; set; }
        public decimal COSTAMNT { get; set; }
        public decimal FRTAMNT { get; set; }
        public decimal MISCAMNT { get; set; }
        public decimal TAXAMNT { get; set; }
        public decimal COMDLRAM { get; set; }
        public decimal CASHAMNT { get; set; }
        public decimal DISTKNAM { get; set; }
        public decimal DISAVAMT { get; set; }
        public decimal DISAVTKN { get; set; }
        public decimal DISCRTND { get; set; }
        public System.DateTime DISCDATE { get; set; }
        public decimal DSCDLRAM { get; set; }
        public short DSCPCTAM { get; set; }
        public decimal WROFAMNT { get; set; }
        public string TRXDSCRN { get; set; }
        public string CSPORNBR { get; set; }
        public string SLPRSNID { get; set; }
        public string SLSTERCD { get; set; }
        public System.DateTime DINVPDOF { get; set; }
        public decimal PPSAMDED { get; set; }
        public decimal GSTDSAMT { get; set; }
        public byte DELETE1 { get; set; }
        public short AGNGBUKT { get; set; }
        public short VOIDSTTS { get; set; }
        public System.DateTime VOIDDATE { get; set; }
        public string TAXSCHID { get; set; }
        public string CURNCYID { get; set; }
        public string PYMTRMID { get; set; }
        public string SHIPMTHD { get; set; }
        public decimal TRDISAMT { get; set; }
        public string SLSCHDID { get; set; }
        public string FRTSCHID { get; set; }
        public string MSCSCHID { get; set; }
        public decimal NOTEINDX { get; set; }
        public System.DateTime Tax_Date { get; set; }
        public byte APLYWITH { get; set; }
        public System.DateTime SALEDATE { get; set; }
        public byte CORRCTN { get; set; }
        public byte SIMPLIFD { get; set; }
        public byte Electronic { get; set; }
        public byte ECTRX { get; set; }
        public decimal BKTSLSAM { get; set; }
        public decimal BKTFRTAM { get; set; }
        public decimal BKTMSCAM { get; set; }
        public decimal BackoutTradeDisc { get; set; }
        public byte Factoring { get; set; }
        public byte DIRECTDEBIT { get; set; }
        public string ADRSCODE { get; set; }
        public System.DateTime DEX_ROW_TS { get; set; }
        public int DEX_ROW_ID { get; set; }
    }
}
