//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace OneCoreData
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbClientesComConfig
    {
        public int idClienteConfig { get; set; }
        public int idEmpresa { get; set; }
        public string idCliente { get; set; }
        public string idVendedor { get; set; }
        public string idAduana { get; set; }
        public string strTipoOp { get; set; }
        public string idPedimento { get; set; }
        public int intDiasCredito { get; set; }
        public int intDiasRetencion { get; set; }
        public int intDiasGracia { get; set; }
        public string strTipoCosto { get; set; }
        public string strIntercia { get; set; }
        public string strNotificacion { get; set; }
        public bool boolActivo { get; set; }
        public System.DateTime dtFechaAlta { get; set; }
        public Nullable<System.DateTime> dtFechaModifica { get; set; }
        public string idUsuarioAlta { get; set; }
        public string idUsuarioModifica { get; set; }
    }
}
